//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandscapeDesignClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorsAndMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsAndMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LandscapeDesignClient.Resources.ErrorsAndMessages", typeof(ErrorsAndMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка сервера..
        /// </summary>
        internal static string e_100 {
            get {
                return ResourceManager.GetString("e_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла непредвиденная ошибка..
        /// </summary>
        internal static string e_101 {
            get {
                return ResourceManager.GetString("e_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно подлючиться к серверу..
        /// </summary>
        internal static string e_102 {
            get {
                return ResourceManager.GetString("e_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык не найден..
        /// </summary>
        internal static string e_103 {
            get {
                return ResourceManager.GetString("e_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание!.
        /// </summary>
        internal static string e_104 {
            get {
                return ResourceManager.GetString("e_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление.
        /// </summary>
        internal static string e_105 {
            get {
                return ResourceManager.GetString("e_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить?.
        /// </summary>
        internal static string e_106 {
            get {
                return ResourceManager.GetString("e_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка входа..
        /// </summary>
        internal static string e_200 {
            get {
                return ResourceManager.GetString("e_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите email..
        /// </summary>
        internal static string e_201 {
            get {
                return ResourceManager.GetString("e_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный email..
        /// </summary>
        internal static string e_202 {
            get {
                return ResourceManager.GetString("e_202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль..
        /// </summary>
        internal static string e_203 {
            get {
                return ResourceManager.GetString("e_203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен быть от 8 до 20 символов включительно, содежать букву верхнего и нижнего регистра, цифру и спецсимвол..
        /// </summary>
        internal static string e_204 {
            get {
                return ResourceManager.GetString("e_204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное имя..
        /// </summary>
        internal static string e_205 {
            get {
                return ResourceManager.GetString("e_205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите подтверждение пароля..
        /// </summary>
        internal static string e_206 {
            get {
                return ResourceManager.GetString("e_206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают..
        /// </summary>
        internal static string e_207 {
            get {
                return ResourceManager.GetString("e_207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный email или пароль..
        /// </summary>
        internal static string e_208 {
            get {
                return ResourceManager.GetString("e_208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким email уже существует..
        /// </summary>
        internal static string e_209 {
            get {
                return ResourceManager.GetString("e_209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код подтверждения недействителен..
        /// </summary>
        internal static string e_210 {
            get {
                return ResourceManager.GetString("e_210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким id уже существует..
        /// </summary>
        internal static string e_211 {
            get {
                return ResourceManager.GetString("e_211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный код..
        /// </summary>
        internal static string e_212 {
            get {
                return ResourceManager.GetString("e_212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователя с таким авторизационным токеном не существует..
        /// </summary>
        internal static string e_213 {
            get {
                return ResourceManager.GetString("e_213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение регистрации недоступно..
        /// </summary>
        internal static string e_214 {
            get {
                return ResourceManager.GetString("e_214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша почта не подтверждена..
        /// </summary>
        internal static string e_215 {
            get {
                return ResourceManager.GetString("e_215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код подтверждения выслан повторно..
        /// </summary>
        internal static string e_216 {
            get {
                return ResourceManager.GetString("e_216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша почту уже подтверждена.
        /// </summary>
        internal static string e_217 {
            get {
                return ResourceManager.GetString("e_217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно получить проекты..
        /// </summary>
        internal static string e_301 {
            get {
                return ResourceManager.GetString("e_301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно получить данные проекта.
        /// </summary>
        internal static string e_302 {
            get {
                return ResourceManager.GetString("e_302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить данные..
        /// </summary>
        internal static string e_303 {
            get {
                return ResourceManager.GetString("e_303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось добавить проект..
        /// </summary>
        internal static string e_304 {
            get {
                return ResourceManager.GetString("e_304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось отредактировать проект..
        /// </summary>
        internal static string e_305 {
            get {
                return ResourceManager.GetString("e_305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось удалить проект..
        /// </summary>
        internal static string e_306 {
            get {
                return ResourceManager.GetString("e_306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось добавить растение..
        /// </summary>
        internal static string e_307 {
            get {
                return ResourceManager.GetString("e_307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось отредактировать растение..
        /// </summary>
        internal static string e_308 {
            get {
                return ResourceManager.GetString("e_308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось удалить растение..
        /// </summary>
        internal static string e_309 {
            get {
                return ResourceManager.GetString("e_309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось добавить строение..
        /// </summary>
        internal static string e_310 {
            get {
                return ResourceManager.GetString("e_310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось отредактировать строение..
        /// </summary>
        internal static string e_311 {
            get {
                return ResourceManager.GetString("e_311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось удалить строение..
        /// </summary>
        internal static string e_312 {
            get {
                return ResourceManager.GetString("e_312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы собираетесь поделиться со всеми. После подтверждения вы не сможете отредактировать или удалить.
        /// </summary>
        internal static string e_313 {
            get {
                return ResourceManager.GetString("e_313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить текстуру..
        /// </summary>
        internal static string e_314 {
            get {
                return ResourceManager.GetString("e_314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое растение.
        /// </summary>
        internal static string e_315 {
            get {
                return ResourceManager.GetString("e_315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование растения.
        /// </summary>
        internal static string e_316 {
            get {
                return ResourceManager.GetString("e_316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое строение.
        /// </summary>
        internal static string e_317 {
            get {
                return ResourceManager.GetString("e_317", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование строения.
        /// </summary>
        internal static string e_318 {
            get {
                return ResourceManager.GetString("e_318", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория не найдена..
        /// </summary>
        internal static string e_319 {
            get {
                return ResourceManager.GetString("e_319", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый проект.
        /// </summary>
        internal static string e_320 {
            get {
                return ResourceManager.GetString("e_320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указатель.
        /// </summary>
        internal static string e_321 {
            get {
                return ResourceManager.GetString("e_321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перемещение.
        /// </summary>
        internal static string e_322 {
            get {
                return ResourceManager.GetString("e_322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить точку.
        /// </summary>
        internal static string e_323 {
            get {
                return ResourceManager.GetString("e_323", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличить.
        /// </summary>
        internal static string e_324 {
            get {
                return ResourceManager.GetString("e_324", resourceCulture);
            }
        }
    }
}
